version: "3.7"
services:
  
  app:
    container_name: bolt_app
    restart: always
    depends_on: 
      - database
    build: .
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      PORT: ${VIRTUAL_PORT}
    volumes:
      - .:/var/www/html/
      - vendor:/var/www/html/vendor/
    networks:
      - nginx-proxy
      - default
    
  composer:
    image: composer:1.8
    depends_on:
      - app
    volumes:
      - .:/app
      - vendor:/app/vendor/
    networks:
      - default
    entrypoint: "composer install --prefer-dist --no-scripts"

  database:
    container_name: ${DB_HOST}
    restart: always
    image: postgres:11-alpine
    volumes:
    - ./data/:/var/lib/postgresql/data
    ports: 
      - ${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - default

volumes:
  app_data:
  vendor:

networks:
  default:
  nginx-proxy:
    external: true